/**
 * This files contains the entity class for the user
 */

/**
 * import all decorator from typeorm
 */
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * The class User is used with the ORM TypeORM to access data in the database table users.
 */
@Entity('users')
export class User {
  /**
   * The ID (primary key) of the table (autogenerated)
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The email address of the user
   */
  @Column({ type: 'varchar', length: 50 })
  email: string;

  /**
   * The hashed password of the user
   * Because of SQL problems (hashedPassword can only be used in ""), we use hashed_password as database column.
   */
  @Column({ type: 'varchar', length: 64, name: 'hashed_password' })
  hashedPassword: string;

  /**
   * The current token of the user (if any ...)
   */
  @Column({ type: 'varchar', length: 255, default: '' })
  token: string;

  /**
   * The timestamp of the last login by the user
   * Because of SQL problems (lastLogin can only be used in ""), we use last_login as database column.
   */
  @Column({ nullable: true, name: 'last_login' })
  lastLogin: Date;
}
