/**
 * This files contains the entity class for the Link
 */

/**
 * Import all decorator from typeorm
 */
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

/**
 * The class Payment is used with the ORM TypeORM to access data in the database table payments.
 */
@Entity('payments')
export class Payment {
  /**
   * The ID (primary key) of the table (autogenerated).
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The id of the document for which the payment is.
   */
  @Column({ type: 'int', name: 'document_id', nullable: false })
  documentId: number;

  /**
   * The type of payment ("COUPON" or "PAYPAL")
   */
  @Column({ type: 'varchar', length: 10, nullable: false })
  type: string;

  /**
   * The paypal payment data (if paypal was used for payment).
   */
  @Column({ type: 'json', name: 'paypal_receipt', nullable: true })
  paypalReceipt: string;

  /**
   * The coupon code (if payment by coupons was used).
   */
  @Column({
    type: 'varchar',
    name: 'coupon_code',
    length: 255,
    nullable: true,
  })
  couponCode: string;

  /**
   * The timestamp at which the record was created in the database.
   */
  @Column({ name: 'created_at', nullable: false })
  createdAt: Date;
}
