/**
 * This files contains the entity class for the coupon
 */

/**
 * import all decorator from typeorm
 */
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

/**
 * The class Coupon is used with the ORM TypeORM to access data in the table coupons
 */
@Entity('coupons')
export class Coupon {
  /**
   * The ID (primary key) of the table (autogenerated)
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The coupon code (unique)
   */
  @Column({ type: 'varchar', length: 25, unique: true })
  code: string;

  /**
   * The datetime when the coupon was used. The coupon is only valid if this value is empty.
   */
  @Column({ name: 'used_at', nullable: true })
  usedAt: Date;
}
