/**
 * This files contains the entity class for the Link
 */

/**
 * import all decorator from typeorm
 */
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

/**
 * The class Link is used with the ORM TypeORM to access data in the database table links.
 */
@Entity('links')
export class Link {
  /**
   * The ID (primary key) of the table (autogenerated)
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The ID of the source document
   */
  @Column({ type: 'int', name: 'source_document_id' })
  sourceDocumentId: number;

  /**
   * The ID of the target document
   */
  @Column({ type: 'int', name: 'target_document_id' })
  targetDocumentId: number;

  /**
   * Create a new instance of the Link class
   * @params source The ID of the source document
   * @params target The ID of the target document
   */
  constructor(source: number, target: number) {
    this.sourceDocumentId = source;
    this.targetDocumentId = target;
  }
}
